Completed code challenge. Running with Node.js
thirdchannel/code-challenge pull request #8
Opened 2019-08-01 01:15 UTC by kevintbradbury

I opted to use Node.js because this is running from a shell script and would be the most lean solution. Please let me know if you have questions.

2019-08-01 11:48 UTC, spullen commented on app.js
> +var keys = ['name','product','gift','gift-value', 'representative'];
The solution should work with any data/template pairings, not just the ones supplied in the test directory (see example in readme). Could you update your solution to handle arbitrary cases as well.

2019-08-01 20:31 UTC, kevintbradbury commented on app.js
> +var keys = ['name','product','gift','gift-value', 'representative'];
Script now obtains keys from template file, looks in data file for equal number of Key/Value pairs.

2019-08-02 14:27 UTC, eliottwiener-thirdchannel requested changes
This is looking really good so far! Just needs a few changes to be perfect. Most importantly, see if you can get it to run against the test suite and pass.

2019-08-02 14:27 UTC, eliottwiener-thirdchannel commented on run.sh
> +       node app.js "$1" "$2" "$3"
`run.sh` should be able to be invoked the way it is invoked in `test.sh`:

https://github.com/kevintbradbury/code-challenge/blob/c243a7f4259663ea5d1fc9b9b45a1f9676b3e018/test.sh#L7

It should work with STDIN and STDOUT, as specified by the `README.md`:

>- Read a data file containing variable bindings from STDIN, parsing it into an in-memory representation.
>...
>- Output the result to STDOUT.
 
Additionally, you should be run the test suite (`./test.sh`) and receive a `Tests passed` result. There are some cases included in the tests that are not handled in your solution. Can you fix them?

2019-08-02 14:27 UTC, eliottwiener-thirdchannel commented on data
> +gift =a SVIKTRA Towel Set
How would your program fare if this line had more whitespace, like:

```
gift                               =a SVIKTRA Towel Set
```

2019-08-02 14:27 UTC, eliottwiener-thirdchannel commented on data
> +gift-value=$20
Try changing the value to `$10` - you might be surprised at the result! See if you can fix the bug.

2019-08-05 13:05 UTC, eliottwiener-thirdchannel approved these changes

2019-08-07 21:04 UTC, closed without merging